<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
	<!-- Load font awesome for glyphicons -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
	<!-- Load Bootstrap v4.0.0-alpha.2 CSS -->
	<link  rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
    <link  rel="stylesheet" href="css/myStyle.css" type="text/css" />
    <script type="text/javascript" src="js/contact.js"></script>
    <title>John Jeong: Portfolio Home</title>
</head>
<body>
<?php
	$result  = "";
	if (isset($_GET['result']) 
		&& ($_GET['result'] == "success"
		|| $_GET['result'] == "error")) { 
		$result = $_GET['result'];
		unset($_GET['result']);
		echo "<script type='text/javascript'> show_results();</script>";
	}
?>
<header>
	<!-- Navigation -->
    <nav class="navbar navbar-dark bg-primary navbar-full navbar-fixed-top">
        <div class="container">
            <a class="navbar-brand" href="http://ABC.COM/"><img class="img-fluid logo-inline" src="images/logo-28.gif" alt="Logo">John Jeong</a>
            <!-- href="<?php echo htmlentities($_SERVER['PHP_SELF']); ?>" -->
            <!-- Toggle Button -->
            <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#nav-content">☰</button> 
            <!-- Nav Content -->
            <div class="collapse navbar-toggleable-xs" id="nav-content">
                <ul class="nav navbar-nav pull-sm-right">
                    <li class="nav-item"><a class="nav-link" href='#home'><span class="fa fa-home" aria-hidden="true"></span> Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="#youtube">YouTube</a></li>
                    <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<!-- Portfolio page -->
<section id="home" class="section-cyan">
	<div class="container clearfix">
		<div class="row" data-toggle="tooltip" data-placement="top" title="HTML card elements below were dynamically generated by jQuery with JSON Data">
			<div class="col-md-12">
				<h2 class="page-header">Portfolio</h2>
                <!-- Generate HTML page with JavaScript from JSON -->
				<div id="portfolios">
				</div>
			</div><!-- end col-md-12 -->
		</div><!-- end row -->
	</div><!--  end container -->
</section>

<!-- YouTube page -->
<section id="youtube" class="section-gray">
	<div class="container clearfix">
		<div class="row">
			<div class="col-md-12">
				<h2 class="page-header">YouTube Channel</h2>
				<!-- 1st row -->
				<div class="row">	
					<!-- Vet Clinic -->
					<div class="col-sm-6 margin-bottom30">
						<div class="embed-responsive embed-responsive-16by9" data-toggle="tooltip" data-placement="top" title="Visual Basic.net, MySQL, DAL Class, Stored Procedure">
							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/FcBo1bKC7rE" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
					<!-- Airline Reservation -->
					<div class="col-sm-6 margin-bottom30">
						<div  class="embed-responsive embed-responsive-16by9" data-toggle="tooltip" data-placement="top" title="Visual Basic.net">
							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/z9y3NafcnPs" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
				</div><!-- end 1st row -->
				
				<!-- 2nd row -->
				<div class="row">	
					<!-- Android app -->
					<div class="col-sm-6 margin-bottom30">
						<div class="embed-responsive embed-responsive-16by9" data-toggle="tooltip" data-placement="top" title="Java, Android Studio 1.5.1">
							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/aakp6iZ4qAk" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
					<!-- Computer Components Warehouse -->
					<div class="col-sm-6 margin-bottom30">
						<div class="embed-responsive embed-responsive-16by9" data-toggle="tooltip" data-placement="top" title="C#, SQL Server, DAL Class">
							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/GAJRiVW8TgU" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
				</div><!-- end 2nd row -->
				
				<!-- 3rd row -->
				<div class="row">	
					<!-- Super Paint -->
					<div class="col-sm-6 margin-bottom30">
						<div class="embed-responsive embed-responsive-16by9" data-toggle="tooltip" data-placement="top" title="Visual Basic.net">
							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/jIcnJeeZejk" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
					<!-- Bubble Sort -->
					<div class="col-sm-6 margin-bottom30">
						<div class="embed-responsive embed-responsive-16by9" data-toggle="tooltip" data-placement="top" title="Visual Basic.net">
							<iframe class="embed-responsive-item" src="https://www.youtube.com/embed/7Rf5a6RUk2k" frameborder="0" allowfullscreen></iframe>
						</div>
					</div>
				</div><!-- end 3rd row -->
			</div><!-- end col-md-12 -->
		</div><!-- end row -->
	</div><!-- end container -->
</section>

<!-- Contact page -->
<section id="contact" class="section-cyan">
	<div class="container clearfix">
		<div class="row">
			<div class="col-md-12">
				<h2 class="page-header">Contact</h2>
				<!-- Embedded Google Map -->
				<div class="row">
					<div class="col-sm-12">
						<div id="map-container"></div>
					</div>
				</div>
				<!-- Show results of the sending message -->
                <div id="contact-results" class="row">
                    <div class="col-sm-12">
                        <?php if ($result == "success") { ?>
                            <div class="alert alert-success">
                                <p class="text-xs-center">Thank you !</p>
                                <p class="text-xs-center">Your message has been successfully sent. I will contact you soon!</p>
                            </div>
                        <?php } else if ($result == "error") { ?>
                            <div class="alert alert-danger">
                                <p class="text-xs-center text-uppercase">Oops !</p>
                                <p class="text-xs-center">Something went wrong. Please try again later.</p>
                            </div>
                        <?php } ?>
                    </div>
                </div>
				<!-- Contact Form -->
				<div class="row">	
					<div class="col-sm-12">
						<form id="contact-form" method="post" action="gdform.php" class="contact-form form">
							<div class="controls">
								<div class="row">
									<div class="col-sm-6">
										<div class="form-group">
											<label for="firstname">Your firstname *</label>
											<input type="text" name="firstname" id="firstname" placeholder="Enter your firstname" required class="form-control">
										</div>
									</div>
									<div class="col-sm-6">
										<div class="form-group">
											<label for="lastname">Your lastname *</label>
											<input type="text" name="lastname" id="lastname" placeholder="Enter your lastname" required class="form-control">
										</div>
									</div>
								</div>
								<div class="form-group">
									<label for="email">Your email *</label>
									<input type="email" name="email" id="email" placeholder="Enter your email" required class="form-control">
								</div>
								<div class="form-group">
									<label for="subject">Subject *</label>
									<input type="text" name="subject" id="subject" placeholder="Enter your subject" required class="form-control">
								</div>
								<div class="form-group">
									<label for="message">Your message for me *</label>
									<textarea rows="4" name="message" id="message" placeholder="Enter your message for me here. I will get back to you within 5 business days" required class="form-control"></textarea>
								</div>
								<div class="text-center">
									<input type="submit"  name="submit" value="Send message" class="btn btn-primary btn-block">
								</div>
							</div>
						</form><!-- end contact form -->	
					</div><!-- end col-sm-12 -->
				</div><!-- end row -->
			</div><!-- end col-md-12 -->
		</div><!-- end row -->
	</div><!-- end container -->
</section>

<footer class="footer">
	<div class="container">
		<span class="text-muted">Bootstrap 4 Landing Pages.</span>
		<br/>
		<span class="text-muted">Copyright © 2016 John Jeong. Images copyright their respective owners.</span>
	</div>
</footer>

<!-- Bootstrap Core JavaScript -->
<script type="text/javascript" src="js/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/tether/1.2.0/tether.min.js"></script>  <!--Tooltips are opt-in for performance reasons-->
<script type="text/javascript" src="js/bootstrap.min.js"></script>
<script> $(document).ready(function(){ $('[data-toggle="tooltip"]').tooltip(); }); </script>
<!-- Google Embeded Map JavaScript -->
<script type="text/javascript" src="http://maps.google.com/maps/api/js"></script>
<!-- mustache.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.2.1/mustache.min.js" type="text/javascript"></script>
<!-- My JavaScript -->
<script type="text/javascript" src="js/myScript.js"></script>
</body>
</html>